name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox]  
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  

      - name: Install dependencies
        run: |
          npm ci

      - name: Run Cypress tests
        run: |
          npx cypress run --browser ${{ matrix.browser }} --headless  # Define o navegador para o teste.
        env:
          CI: true

      - name: Generate Allure report
        run: |
          npx allure generate cypress/allure-results --clean -o cypress/allure-report
        continue-on-error: true

      - name: Upload Allure report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: cypress/allure-report
